# backend/app/OM/OM_FacultyService.py
# -----------------------------------------------------------------------------
# OM mirror of CHAIR Faculty Service.
#
# This module intentionally reuses the same data model and business logic as
# CHAIR_FacultyService, but exposes it under the OM router prefix so that
# Office of the Mission (OM) users can access the feature via the OM UI.
#
# IMPORTANT:
# - Data is stored in the same collections (faculty_service, etc.)
# - Notifications generated by the faculty service workflow are still targeted
#   at department chair user(s) and continue to use the chair route in meta.
# -----------------------------------------------------------------------------

# NOTE: We keep this file as a lightweight wrapper to avoid logic drift.

from ..CHAIR.CHAIR_FacultyService import (  # noqa: F401
    fs_options,
    fs_list,
    fs_create,
    fs_send,
    fs_respond,
    fs_reject,
    fs_restore,
)

from fastapi import APIRouter


router = APIRouter(prefix="/om/faculty-service", tags=["om", "faculty-service"])

# Re-register the same handlers under the OM router.
router.add_api_route("/options", fs_options, methods=["GET"])
router.add_api_route("/list", fs_list, methods=["GET"])
router.add_api_route("/create", fs_create, methods=["POST"])
router.add_api_route("/send/{fs_id}", fs_send, methods=["POST"])
router.add_api_route("/respond/{fs_id}", fs_respond, methods=["POST"])
router.add_api_route("/reject/{fs_id}", fs_reject, methods=["POST"])
router.add_api_route("/restore/{fs_id}", fs_restore, methods=["POST"])
