services:
  mongo-stg:
    image: mongo:7
    container_name: mongo-stg
    command: ["--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_staging:/data/db
      - /opt/AnimoAssign3-staging/db/seed:/docker-entrypoint-initdb.d:ro
    ports:
      - "127.0.0.1:27018:27017"   # host-only (safer)
    restart: unless-stopped

  backend:
    # Build from your backend source (adjust path if different)
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-stg
    environment:
      # what your app typically reads
      MONGODB_URI: ${BACKEND_MONGODB_URI}
      # optional extra alias if your app uses this name somewhere
      BACKEND_MONGODB_URI: ${BACKEND_MONGODB_URI}
    depends_on:
      - mongo-stg
    ports:
      - "18000:8000"
    restart: unless-stopped

  analytics:
    # Build from your analytics source (adjust path if different)
    build:
      context: ../analytics
      dockerfile: Dockerfile
    container_name: analytics-stg
    environment:
      # most apps read MONGODB_URI; keep both to be safe
      MONGODB_URI: ${ANALYTICS_MONGODB_URI}
      ANALYTICS_MONGODB_URI: ${ANALYTICS_MONGODB_URI}
    depends_on:
      - mongo-stg
    ports:
      - "18100:8000"
    restart: unless-stopped

  frontend-stg:
    container_name: frontend-stg
    build:
      context: ../frontend            # your actual frontend dir
      dockerfile: Dockerfile
      args:
        VITE_BASE: "${VITE_BASE:-/staging/}"
    ports:
      - "18080:80"
    depends_on:
      - backend
      - analytics
    restart: unless-stopped

volumes:
  mongo_data_staging:
