name: Deploy Production (S1 & S2)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Backend tests (best-effort)
        working-directory: backend
        run: |
          python -m pip install -r requirements.txt || true
          pytest -q || true

      - name: Analytics tests (best-effort)
        working-directory: analytics
        run: |
          python -m pip install -r requirements.txt || true
          pytest -q || true

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [s1, s2]   # keep static; choose credentials via expressions below
    steps:
      - name: Trust host key (${{ matrix.target }})
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ matrix.target == 's1' && vars.S1_PORT || vars.S2_PORT }}" \
                      "${{ matrix.target == 's1' && vars.S1_HOST || vars.S2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to ${{ matrix.target }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ matrix.target == 's1' && vars.S1_HOST || vars.S2_HOST }}
          port:     ${{ matrix.target == 's1' && vars.S1_PORT || vars.S2_PORT }}
          username: ${{ matrix.target == 's1' && vars.S1_USER || vars.S2_USER }}
          key:      ${{ matrix.target == 's1' && secrets.S1_KEY || secrets.S2_KEY }}
          script: |
            set -Eeuo pipefail

            if [ ! -d /opt/AnimoAssign3/.git ]; then
              mkdir -p /opt/AnimoAssign3
              cd /opt/AnimoAssign3
              git clone https://github.com/HIEB1I/AnimoAssign3.git .
            fi

            cd /opt/AnimoAssign3
            git fetch --all --prune
            git checkout main
            git pull --ff-only

            # Resolve compose + env-file from repo (docker/ preferred)
            FILE=""
            [ -f docker/compose.prod.yml ] && FILE=docker/compose.prod.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.prod.yml ] && FILE=docker/docker-compose.prod.yml
            [ -z "$FILE" ] && [ -f docker/compose.yml ] && FILE=docker/compose.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.yml ] && FILE=docker/docker-compose.yml
            [ -z "$FILE" ] && [ -f docker-compose.yml ] && FILE=docker-compose.yml
            [ -z "$FILE" ] && { echo "No compose file found"; exit 1; }

            ENVF=""
            [ -f docker/.env.prod ] && ENVF=docker/.env.prod
            [ -z "$ENVF" ] && [ -f .env.prod ] && ENVF=.env.prod  # repo root fallback (present in your repo)
            [ -z "$ENVF" ] && { echo "Missing prod env file (docker/.env.prod or .env.prod)"; exit 1; }

            export COMPOSE_PROJECT_NAME=animo_prod
            docker compose -f "$FILE" --env-file "$ENVF" up -d --build

            # Example smoke checks (tweak as needed)
            curl -fsS  http://127.0.0.1:18000/health || (docker compose -f "$FILE" logs backend && exit 1)
            curl -fsS  http://127.0.0.1:19000/health || (docker compose -f "$FILE" logs analytics && exit 1)
            curl -fsSI http://127.0.0.1:8080         || (docker compose -f "$FILE" logs frontend && exit 1)

            docker system prune -f
