name: Deploy Staging (S1)

on:
  push:
    branches: [staging]
  workflow_dispatch: {}

concurrency:
  group: deploy-staging
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: staging }

      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Backend tests (best-effort)
        working-directory: backend
        run: |
          python -m pip install -r requirements.txt || true
          pytest -q || true

      - name: Analytics tests (best-effort)
        working-directory: analytics
        run: |
          python -m pip install -r requirements.txt || true
          pytest -q || true

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    # Pull repo VARIABLES into the job environment
    env:
      S1_HOST: ${{ vars.S1_HOST }}
      S1_PORT: ${{ vars.S1_PORT }}
      S1_USER: ${{ vars.S1_USER }}

    steps:
      - name: Validate inputs
        run: |
          for v in S1_HOST S1_PORT S1_USER; do
            if [ -z "${!v}" ]; then
              echo "::error ::$v is empty. Set repository variable '$v' (Settings → Actions → Variables)."
              exit 1
            fi
          done
          echo "Using S1_HOST=$S1_HOST S1_PORT=$S1_PORT S1_USER=$S1_USER"

      - name: Trust S1 host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$S1_PORT" "$S1_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to S1 (staging)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.S1_HOST }}
          port:     ${{ env.S1_PORT }}
          username: ${{ env.S1_USER }}
          key:      ${{ secrets.S1_KEY }}
          script: |
            set -Eeuo pipefail

            # Ensure staging checkout exists
            if [ ! -d /opt/AnimoAssign3-staging/.git ]; then
              mkdir -p /opt/AnimoAssign3-staging
              cd /opt/AnimoAssign3-staging
              git clone https://github.com/HIEB1I/AnimoAssign3.git .
            fi

            cd /opt/AnimoAssign3-staging
            git fetch --all --prune
            git checkout staging
            git pull --ff-only

            # Resolve compose + env file from repo
            FILE=""
            [ -f docker/compose.staging.yml ] && FILE=docker/compose.staging.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.staging.yml ] && FILE=docker/docker-compose.staging.yml
            [ -z "$FILE" ] && [ -f docker/compose.yml ] && FILE=docker/compose.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.yml ] && FILE=docker/docker-compose.yml
            [ -z "$FILE" ] && [ -f docker-compose.yml ] && FILE=docker-compose.yml
            [ -z "$FILE" ] && { echo "No compose file found"; exit 1; }

            ENVF=""
            [ -f docker/.env.staging ] && ENVF=docker/.env.staging
            [ -z "$ENVF" ] && [ -f .env.staging ] && ENVF=.env.staging
            [ -z "$ENVF" ] && { echo "Missing staging env file (docker/.env.staging or .env.staging)"; exit 1; }

            export COMPOSE_PROJECT_NAME=animo_staging
            docker compose -f "$FILE" --env-file "$ENVF" up -d --build

            # Smoke checks (adjust ports if needed)
            curl -fsS  http://127.0.0.1:18010/health || (docker compose -f "$FILE" logs backend && exit 1)
            curl -fsS  http://127.0.0.1:19010/health || (docker compose -f "$FILE" logs analytics && exit 1)
            curl -fsSI http://127.0.0.1:8081         || (docker compose -f "$FILE" logs frontend && exit 1)

            docker system prune -f
