name: Deploy Staging (S1)

on:
  push:
    branches: [staging]
  workflow_dispatch: {}

concurrency:
  group: deploy-staging
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging

      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Backend tests (best-effort)
        working-directory: backend
        run: |
          python -m pip install -r requirements.txt || true
          pytest -q || true

      - name: Analytics tests (best-effort)
        working-directory: analytics
        run: |
          python -m pip install -r requirements.txt || true
          pytest -q || true

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    env:
      S1_HOST: ${{ secrets.S1_HOST }}
      S1_PORT: ${{ secrets.S1_PORT }}
      S1_USER: ${{ secrets.S1_USER }}
      S1_KEY:  ${{ secrets.S1_KEY }}

    steps:
      - name: Validate inputs
        run: |
          for v in S1_HOST S1_PORT S1_USER S1_KEY; do
            if [ -z "${!v}" ]; then
              echo "::error ::$v is empty. Add it in Settings → Secrets → Actions."
              exit 1
            fi
          done
          echo "Using $S1_USER@$S1_HOST:$S1_PORT"

      - name: Trust S1 host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$S1_PORT" "$S1_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to S1 (staging)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.S1_HOST }}
          port:     ${{ env.S1_PORT }}
          username: ${{ env.S1_USER }}
          key:      ${{ env.S1_KEY }}
          script: |
            set -Eeuo pipefail

            # Ensure checkout exists
            if [ ! -d /opt/AnimoAssign3-staging/.git ]; then
              mkdir -p /opt/AnimoAssign3-staging
              cd /opt/AnimoAssign3-staging
              git clone https://github.com/HIEB1I/AnimoAssign3.git .
            fi

            cd /opt/AnimoAssign3-staging

            # Force HTTPS for GitHub remotes (avoid SSH on the server)
            unset GIT_SSH_COMMAND || true
            git config --global url.https://github.com/.insteadof git@github.com:
            git config --global url.https://github.com/.insteadof ssh://git@github.com/
            git config --global --add safe.directory /opt/AnimoAssign3-staging
            git remote set-url origin https://github.com/HIEB1I/AnimoAssign3.git

            git fetch --all --prune
            git checkout staging
            git pull --ff-only

            # Resolve compose + env file from repo
            FILE=""
            [ -f docker/docker-compose.staging.yml ] && FILE=docker/docker-compose.staging.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.staging.yml ] && FILE=docker/docker-compose.staging.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.staging.yml] && FILE=docker/docker-compose.staging.yml
            [ -z "$FILE" ] && [ -f docker/docker-compose.staging.yml ] && FILE=docker/docker-compose.staging.yml
            [ -z "$FILE" ] && [ -f docker-compose.staging.yml] && FILE=docker-compose.staging.yml
            [ -z "$FILE" ] && { echo "No compose file found"; exit 1; }

            ENVF=""
            [ -f docker/staging.env ] && ENVF=docker/staging.env
            [ -z "$ENVF" ] && [ -f staging.env ] && ENVF=staging.env
            [ -z "$ENVF" ] && { echo "Missing staging env file (docker/staging.env or staging.env)"; exit 1; }

            export COMPOSE_PROJECT_NAME=animo_staging

            # ---- PRE-CLEAN to avoid name conflicts with hardcoded container_name ----
            docker compose -f "$FILE" --env-file "$ENVF" down --remove-orphans || true

            # Remove any leftover containers that were created by older/other projects
            # (keep names EXACT — they match your compose `container_name` values)
            for c in backend-stg analytics-stg frontend-stg mongo-stg; do
              docker rm -f "$c" 2>/dev/null || true
            done
            # ------------------------------------------------------------------------


            docker compose -f "$FILE" --env-file "$ENVF" up -d --build

            # Optional: verify required envs exist (uncomment if you want strict checks)
            # grep -E "^(MONGO_INITDB_ROOT_USERNAME|MONGO_INITDB_ROOT_PASSWORD|BACKEND_MONGODB_URI|ANALYTICS_MONGODB_URI)=" "$ENVF" >/dev/null || \
            # { echo "One or more Mongo/URI envs missing in $ENVF"; exit 1; }

            # Smoke checks (adjust ports if your compose uses different ones)
            curl -fsS  http://127.0.0.1:18010/health || (docker compose -f "$FILE" logs backend && exit 1)
            curl -fsS  http://127.0.0.1:19010/health || (docker compose -f "$FILE" logs analytics && exit 1)
            curl -fsSI http://127.0.0.1:8081         || (docker compose -f "$FILE" logs frontend && exit 1)

            docker system prune -f
